steps:

# - name: 'gcr.io/cloud-builders/git'
#   entrypoint: 'sh'
#   args:
#     - '-c'
#     - |
#       mkdir -p /root/.ssh
#   volumes:
#     - name: 'volume'
#     - path: '/root'
  
# Step 1: Generate SSH key pair
# - name: 'gcr.io/cloud-builders/git'
#   entrypoint: 'sh'
#   args:
#     - '-c'
#     - |
#       ssh-keygen -t rsa -b 4096 -C "your_email@example.com" -N "" -f /some/id_rsa


# # Step 2: Add SSH key to your GitHub account
# - name: 'gcr.io/cloud-builders/git'
#   entrypoint: 'sh'
#   args:
#     - '-c'
#     - |
#       git config --global user.email "manikanthpolice18@gmail.com"
#       git config --global user.name "Manikanth1811"
#       mkdir -p /root/.ssh
#       echo -e "Host github.com\n\tHostName github.com\n\tIdentityFile /root/.ssh/id_rsa\n" >> /root/.ssh/config
#       ssh-keyscan github.com >> /root/.ssh/known_hosts
#       cat /some/id_rsa >> /root/.ssh/id_rsa.pub
#   volumes:
#     - name: 'volume'
#     - path: '/some'

# Step 3: Clone repository and push changes
# - name: 'gcr.io/cloud-builders/git'
#   entrypoint: 'sh'
#   args:
#     - '-c'
#     - |
#       git clone git@github.com:manikanth1811/react-article-display.git



- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
    - '-c'
    - 'chmod 666 deploy/helm/values.yaml && echo "Changed permissions of values.yaml"'


- name: 'mikefarah/yq'
  entrypoint: sh
  args:
  - '-c'
  - |
    yq e '.image."tag"' deploy/helm/values.yaml -i && \
    yq e '.image."tag"=$SHORT_SHA'

- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      git add -A

- name: 'gcr.io/cloud-builders/git'
  args: ['push', 'https://github.com/manikanth1811/react-article-display.git', 'main']

# - name: 'gcr.io/cloud-builders/git'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       export GIT_TOKEN=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
#       cd react-article-display/
#       git add -A
#       git commit -m "Updated with build ${BUILD_ID} from ${REPO_NAME} commit ${COMMIT_SHA}"
#       git push origin master
#   volumes:
#     - name: 'volume'
#     - path: '/some'


- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f' , 'react-article-display/Dockerfile', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/docker-repo/react-app:$SHORT_SHA', '.']
images: ['us-west2-docker.pkg.dev/$PROJECT_ID/docker-repo/react-app:$SHORT_SHA']


options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: '299138380108@cloudbuild.gserviceaccount.com'

