steps:

  # Step 1: Generate SSH key pair
  - name: 'gcr.io/cloud-builders/ssh'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        ssh-keygen -t rsa -b 4096 -C "your_email@example.com" -N "" -f /root/.ssh/id_rsa

  # Step 2: Add SSH key to your GitHub account
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        git config --global user.email "manikanthpolice18@gmail.com"
        git config --global user.name "Manikanth1811"
        echo -e "Host github.com\n\tHostName github.com\n\tIdentityFile /root/.ssh/id_rsa\n" >> /root/.ssh/config
        ssh-keyscan github.com >> /root/.ssh/known_hosts
        cat /root/.ssh/id_rsa.pub

  # Step 3: Clone repository and push changes
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        git clone git@github.com:manikanth1811/react-article-display.git


- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
    - '-c'
    - 'chmod 666 react-article-display/deploy/helm/values.yaml && echo "Changed permissions of values.yaml"'


- name: 'mikefarah/yq'
  entrypoint: sh
  args:
  - '-c'
  - |
    yq e '.image."tag"' react-article-display/deploy/helm/values.yaml -i && \
    yq e '.image."tag"=$SHORT_SHA'



- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      export GIT_TOKEN=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
      cd react-article-display/
      git add -A
      git commit -m "Updated with build ${BUILD_ID} from ${REPO_NAME} commit ${COMMIT_SHA}"
      git push origin master


- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f' , 'react-article-display/Dockerfile', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/docker-repo/react-app:$SHORT_SHA', '.']
images: ['us-west2-docker.pkg.dev/$PROJECT_ID/docker-repo/react-app:$SHORT_SHA']


options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: '299138380108@cloudbuild.gserviceaccount.com'

