steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
    - '-c'
    - 'chmod 666 deploy/helm/values.yaml && echo "Changed permissions of values.yaml"'


- name: 'mikefarah/yq'
  entrypoint: sh
  args:
  - '-c'
  - |
    yq e '.image."tag"' deploy/helm/values.yaml -i && \
    yq e '.image."tag"=$SHORT_SHA'



- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      export GIT_TOKEN=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
      git add -A
      git commit -m "Updated with build ${BUILD_ID} from ${REPO_NAME} commit ${COMMIT_SHA}"
      git push origin master


- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f' , 'Dockerfile', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/docker-repo/react-app:$SHORT_SHA', '.']
images: ['us-west2-docker.pkg.dev/$PROJECT_ID/docker-repo/react-app:$SHORT_SHA']


options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: '299138380108@cloudbuild.gserviceaccount.com'

