steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  args:
    - '-c'
    - 'chmod 666 deploy/helm/values.yaml && echo "Changed permissions of values.yaml"'


- name: 'mikefarah/yq'
  entrypoint: sh
  args:
  - '-c'
  - |
    yq e '.image."tag"' deploy/helm/values.yaml -i && \
    yq e '.image."tag"=$SHORT_SHA'



- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      export GIT_TOKEN=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
      # git config --global user.name manikanth1811
      # git config --global user.email manikanthpolice18@gmail.com
      git add -A
      git commit -m "Updated with build ${BUILD_ID} from ${REPO_NAME} commit ${COMMIT_SHA}"
      git push origin master


- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f' , 'Dockerfile', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/docker-repo/react-app:$SHORT_SHA', '.']
images: ['us-west2-docker.pkg.dev/$PROJECT_ID/docker-repo/react-app:$SHORT_SHA']


options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: '299138380108@cloudbuild.gserviceaccount.com'


# steps:
#   # Clone repository.
#   - name: 'gcr.io/cloud-builders/git'
#     args: ['clone', 'https://github.com/manikanth1811/react-article-display.git', 'repo']
#     # Use 'git checkout' to switch to a different branch or commit.
#     # Example: ['git', '-C', 'repo', 'checkout', 'my-branch']
#     # Or use the 'dir' option to change the working directory for subsequent steps.

#   # Update YAML file.
#   - name: 'docker.io/library/python:3.9.6-buster'
#     entrypoint: 'sh'
#     args:
#       - '-c'
#       - |
#         SHORT_SHA=$SHORT_SHA
#         pip install -U pip
#         pip install yq
#         yq eval -i ' = env(SHORT_SHA)' /react-article-display/deploy/helm/values.yaml
#   # Build and push Docker image to Container Registry.
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       - 'build'
#       - '-t'
#       - 'gcr.io/$PROJECT_ID/my-image:$SHORT_SHA'
#       - '.'
#       - '-f'
#       - 'Dockerfile'
#     # Replace with your desired service account email address.
#     # Example: 'my-service-account@my-project-id.iam.gserviceaccount.com'.
#     serviceAccount: 'my-service-account@my-project-id.iam.gserviceaccount.com'

# options:
#   logging: CLOUD_LOGGING_ONLY

# # Minimum required IAM roles for a service account that builds and pushes
# # Docker images to Container Registry.
# # Replace with your desired service account email address.
# # Example: 'my-service-account@my-project-id.iam.gserviceaccount.com'.
# serviceAccount: 'my-service-account@my-project-id.iam.gserviceaccount.com'
# substitutions:
#   _CLOUD_BUILD_MACHINE_TYPE: 'N1_HIGHCPU_8'
#   _DOCKER_IMAGE: 'gcr.io/$PROJECT_ID/my-image:$SHORT_SHA'
#   _DOCKER_REGISTRY: 'gcr.io'
#   _DOCKER_REGISTRY_PROJECT_ID: '$PROJECT_ID'
#   _DOCKERFILE: 'Dockerfile'
#   _SOURCE_PATH: '.'
#   _BUILD_CONTEXT: '.'
#   _DOCKER_BUILD_COMMAND: |
#     docker build \
#       --tag ${_DOCKER_IMAGE} \
#       --file ${_DOCKERFILE} \
#       ${_BUILD_CONTEXT}


# steps:
# - name: 'gcr.io/cloud-builders/git'
#   args:
#   - 'clone'
#   - '--single-branch'
#   - '--branch'
#   - 'main'
#   - 'https://github.com/manikanth1811/react-article-display.git'

# - name: 'mikefarah/yq'
#   entrypoint: sh
#   args:
#   - '-c'
#   - |
#     yq e '.image."tag"' deploy/helm/values.yaml -i && \
#     yq e '.image."tag"=0.1.2'

# - name: 'gcr.io/cloud-builders/git'
#   args:
#   - 'config'
#   - '--global'
#   - 'user.email'
#   - 'manikanthpolice18@gmail.com'
  
# - name: 'gcr.io/cloud-builders/git'
#   args:
#   - 'config'
#   - '--global'
#   - 'user.name'
#   - 'manikanth1811'
  
# - name: 'gcr.io/cloud-builders/git'
#   args:
#   - 'commit'
#   - '-m'
#   - 'Update database-url value in config.yaml'
  
# - name: 'gcr.io/cloud-builders/git'
#   args:
#   - 'push'
#   - 'origin'
#   - 'main'
