version: "1.0"

stages:
  - "clone"
  - "build"
  - "deploy"
  
steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "anais-codefresh/react-article-display"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "anaisurlichs/react-article-display"
    working_directory: "./react-article-display"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"

  deploy:
    type: "helm"
    working_directory: "./react-article-display"
    arguments:
      action: "install"
      chart_name: "charts/example-chart"
      release_name: "example-chart"
      helm_version: 3.0.2
      kube_context: "anais-cluster@codefresh-sa"
    stage: "deploy"
