apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-application
  annotations:
    app.komodor.com/app: https://github.com/AnaisUrlichs/react-article-display/
    app.komodor.com/app.ref: kustomize
    app.komodor.com/notification.deploy.slack: "#deploy"
    app.komodor.com/notification.alert.slack: "#p1-health-issues"
    deployment.kubernetes.io/revision: "1"
  labels:
    app.kubernetes.io/instance: "react-app"
spec:
  replicas: 2
  selector:
    matchLabels:
      run: react-application
  template:
    metadata:
      labels:
        run: react-application
    spec:
      containers:
      - name: react-application
        image: anaisurlichs/react-example-app:1.0.0
        ports:
          - containerPort: 80
        imagePullPolicy: Always