apiVersion: v1
kind: Service
metadata:
  labels:
    run: react-application
  name: react-application
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: react-application
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-application
spec:
  replicas: 2
  selector:
    matchLabels:
      run: react-application
  template:
    metadata:
      labels:
        run: react-application
    spec:
      containers:
      - image: anaisurlichs/react-example-app:822b665bcf2b50da74b1e2e65f0787fa46125d80
        imagePullPolicy: Always
        name: react-application
        ports:
        - containerPort: 80
