name: ci

on:
  pull_request:
    branches: master 
env:
  DOCKER_TAG: |
    ${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.head.sha }}  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug action
        uses: hmarr/debug-action@v2.0.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}     
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: manojsaikumar/react-article-display:${{ env.DOCKER_TAG }}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUBTOKEN}}