name: Build and Deploy to GKE
on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          gcloud_service_key: ${{ secrets.GCP_CREDENTIALS }} 
          project_id: tactile-wave-383702
          image_name: docker-repo/react-app
          image_tag: latest
          dockerfile: Dockerfile
          context: .
