# name: Build and Deploy to GKE
# on:
#   push:
#     branches:
#       - main
# jobs:
#   setup-build-publish-deploy:
#     name: Setup, Build, Publish, and Deploy
#     runs-on: ubuntu-latest
#     environment: production
#     permissions:
#       contents: write
#       id-token: write
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - id: auth
#         uses: google-github-actions/auth@v0
#         with:
#           credentials_json: ${{ secrets.GCP_CREDENTIALS }}
#       - name: Replace tag with GitHub SHA
#         run: sed -i "s/tag:.*/tag: ${{ github.sha }}/g" deploy/helm/values.yaml
#       - uses: stefanzweifel/git-auto-commit-action@v4
#         with:
#           commit_message: new version
#       - name: Build
#         run: >-
#           docker build \
#             --tag "us-west2-docker.pkg.dev/tactile-wave-383702/docker-repo/react-app:$GITHUB_SHA" \
#             --build-arg GITHUB_SHA="$GITHUB_SHA" \
#             .
#       - name: Publish
#         run: docker push
#           "us-west2-docker.pkg.dev/tactile-wave-383702/docker-repo/react-app:$GITHUB_SHA"


name: Build and Deploy to GKE
on:
  push:
    branches:
      - main
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Replace tag with GitHub SHA
        run: yq eval -i '.image.tag = env.GITHUB_SHA' deploy/helm/values.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: new version
      - name: Build
        run: >-
          docker build \
            --tag "us-west2-docker.pkg.dev/tactile-wave-383702/docker-repo/react-app:$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            .
      - name: Publish
        run: docker push "us-west2-docker.pkg.dev/tactile-wave-383702/docker-repo/react-app:$GITHUB_SHA"
