name: Deployment CI

on:
  push:
    branches: 
      - kustomize

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/react-example-app:4.0.0

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
      - name: Set up Kustomize
        run: |-
          curl --location https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.2.0/kustomize_v4.2.0_linux_amd64.tar.gz | tar xz
          chmod u+x ./kustomize

      - name: Deploy
        run: |-
          cd ./manifests
          kustomize edit set image ${{ secrets.DOCKER_USERNAME }}/react-example-app:4.0.0
          kustomize build ./ > ../kustomization/manifests.yaml
  
      - name: datree
        run: |-
          curl https://get.datree.io | /bin/bash
          datree test ./kustomization/manifests.yaml
