name: Deployment CI

on:
  push:
    branches: 
      - kustomize

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/react-example-app:4.0.0

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  
      - name: Set up Kustomize
        run: |-
          curl --location https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.2.0/kustomize_v4.2.0_linux_amd64.tar.gz | tar xz
          chmod u+x ./kustomize

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
        cd manifests
        kustomize edit set image ${{ secrets.DOCKER_USERNAME }}/react-example-app:$GITHUB_SHA
        cat kustomization.yaml
        kustomize build ./ > ../kustomization/manifests.yaml
        cat ../kustomization/manifests.yaml
          
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump docker tag"

      - uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          branch: kustomize

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: datree
        run: |-
          curl https://get.datree.io | /bin/bash
          datree test ./kustomization/manifests.yaml
        continue-on-error: true
