name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/anaisurlichs/react-app:${{ github.sha }} .
      
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@add-support-for-trivy-config
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          trivy-config: ./trivy-config.yaml
          
